# Generated by Django 4.0.5 on 2022-09-11 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('caption', models.TextField(max_length=200, verbose_name='کپشن پست')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پستها',
                'db_table': 't_posts',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajaxtest.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'لایک',
                'verbose_name_plural': 'لایک ها',
                'db_table': 't_like',
            },
        ),
    ]
