# Generated by Django 4.0.5 on 2022-09-13 14:58

import apps.DRFtest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRFtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField(default=0)),
                ('register_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=apps.DRFtest.models.image_path)),
            ],
        ),
    ]
