# Generated by Django 4.0.5 on 2022-09-13 15:01

import apps.DRFtest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRFtest', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/product/noimage.jpg', upload_to=apps.DRFtest.models.image_path),
        ),
    ]
