# Generated by Django 4.0.5 on 2022-08-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(max_length=3000, verbose_name='پیام')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
        ),
    ]
