# Generated by Django 4.0.5 on 2022-07-16 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('family', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=20)),
                ('slug', models.SlugField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
    ]
