# Generated by Django 4.0.5 on 2022-07-27 06:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=300, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(max_length=100)),
                ('article_text', models.TextField(verbose_name='متن اصلی')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نوشته شده')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('status', models.CharField(choices=[('Draft', 'پیش نویس'), ('publish', 'منتشر شده')], default='Draft', max_length=40, verbose_name='وضعیت مقاله')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='نویسنده')),
            ],
        ),
    ]
