# Generated by Django 4.0.5 on 2022-07-27 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiefEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('family', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('title', models.CharField(max_length=100, verbose_name='نام انتشارات')),
                ('chiefeditor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.chiefeditor', verbose_name='سردبیر')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='publication',
            field=models.ManyToManyField(to='blog.publication', verbose_name='سردبیر/انتشارات'),
        ),
    ]
