# Generated by Django 4.0.5 on 2022-08-30 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_options_alter_author_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='articleimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن اصلی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('main_img', models.ImageField(upload_to='images/article', verbose_name='عکس اصلی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'db_table': 'T_articleimg',
                'ordering': ['title', 'is_active'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['article_title', 'is_active'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', 'پیش نویس'), ('publish', 'منتشر شده'), ('unknown', 'نامشخص')], default='Draft', max_length=40, verbose_name='وضعیت مقاله'),
        ),
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=20, verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='author',
            name='family',
            field=models.CharField(max_length=30, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=30, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='author',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='author',
            name='url_field',
            field=models.URLField(default=None, verbose_name='آدرس سایت'),
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 18)), name='age__gte__18'),
        ),
    ]
