# Generated by Django 4.0.5 on 2022-10-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_articleimg_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleimg',
            options={'ordering': ['title', 'is_active'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'عکس مقالات'},
        ),
        migrations.AlterField(
            model_name='articleimg',
            name='main_img',
            field=models.ImageField(upload_to='', verbose_name='عکس اصلی'),
        ),
    ]
